services:
  identidock:
    container_name: compose-test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - "dnmonster"
      - "redis"

  dnmonster:
    image: amouat/dnmonster/latest

  redis:
    image: redis/7.0
